name: Maven Release & Deploy
on: workflow_dispatch
jobs:
   release:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout project
           uses: actions/checkout@v3
         - name: Set up JDK 21
           uses: actions/setup-java@v3
           with:
              java-version: 21
              distribution: 'zulu' # Alternative distribution options are available.
         - name: Java Maven release
           uses: qcastel/github-actions-maven-release@v1.12.41
           env:
              JAVA_HOME: /usr/lib/jvm/java-21-openjdk/
           with:
              version-patch: true
              release-branch-name: main
              gpg-enabled: true
              gpg-key-id: ${{secrets.RELEASE_GPG_KEY_ID}}
              gpg-key: ${{secrets.RELEASE_GPG_KEY}}
              git-release-bot-name: ${{secrets.RELEASE_USER_NAME}}
              git-release-bot-email: ${{secrets.RELEASE_USER_EMAIL}}
              access-token: ${{secrets.RELEASE_GITHUB_TOKEN}}
              maven-servers: ${{ secrets.MVN_REPO_SERVERS }}
              maven-args: -Prelease -DskipTests -Dgpg.keyname=${{secrets.RELEASE_GPG_KEY_ID}} -Dgpg.passphrase=